create database DEALERSHIP;

CREATE table EMPLOYEES (
   EMPLOYEE_ID INT PRIMARY KEY ,
   EMPLOYEE_NAME VARCHAR(50) NOT NULL,
   WORKDAY TIMESTAMP NOT NULL
);

CREATE TABLE CAR_DETAILS (
   SERIAL_NUM VARCHAR(50) PRIMARY KEY ,
   MODEL_NAME VARCHAR(50) NOT NULL,
   MANUFACTURER VARCHAR(50) NOT null,
   WEIGHT FLOAT not null,
   PRICE FLOAT not NULL
);

CREATE TABLE SALES (
   SALE_ID INT PRIMARY KEY ,
   EMPLOYEE_NAME VARCHAR(50) NOT NULL,
   DATE_SOLD TIMESTAMP not null,
   CUST_NAME VARCHAR(50) not null,
   CUST_PHONE INT not null,
   SERIAL_NUM VARCHAR(50) not NULL
   
);

-- QUERIES

-- Q1 
-- select CUST_NAME, SUM(PRICE) from SALES left join CAR_DETAILS group by CUST_NAME;

--Q2
-- SELECT MANUFACTURER, COUNT(*) AS QTY FROM SALES LEFT JOIN CAR DETAILS GROUP BY MANUFACTURER 
-- ORDER BY QTY DESC LIMIT 3;
